name: Build and test

on:
  push:
    branches:
      - test-macoshang

jobs:

  macos:
    name: Build and test (MacOS)
    runs-on: macos-11

    steps:

    - uses: actions/checkout@v2
    - name: Initialize modules list
      run: |
        echo "MODULES_TO_TEST=pytket-honeywell" >> $GITHUB_ENV

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build and test (3.9)
      run: |
        ./.github/workflows/build-test nomypy

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build and test (3.10)
      run: |
        ./.github/workflows/build-test nomypy
