name: Build and test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - 'wheel/**'
  release:
    types:
      - created
      - edited

env:
  IQSHARP_TELEMETRY_OPT_OUT: 1
  # Env variables for pytket extensions remote tests
  # pytket-braket
  PYTKET_REMOTE_BRAKET_ACCESS_KEY_ID: ${{ secrets.PYTKET_REMOTE_BRAKET_ACCESS_KEY_ID }}
  PYTKET_REMOTE_BRAKET_ACCESS_KEY_SECRET: ${{ secrets.PYTKET_REMOTE_BRAKET_ACCESS_KEY_SECRET }}
  PYTKET_REMOTE_BRAKET_REGION: ${{ secrets.PYTKET_REMOTE_BRAKET_REGION }}
  PYTKET_REMOTE_BRAKET_BUCKET: ${{ secrets.PYTKET_REMOTE_BRAKET_BUCKET }}
  PYTKET_REMOTE_BRAKET_FOLDER: ${{ secrets.PYTKET_REMOTE_BRAKET_FOLDER }}
  # pytket-iqm
  PYTKET_REMOTE_IQM_USERNAME: ${{ secrets.PYTKET_REMOTE_IQM_USERNAME }}
  PYTKET_REMOTE_IQM_APIKEY: ${{ secrets.PYTKET_REMOTE_IQM_APIKEY }}
  # pytket-qiskit
  PYTKET_REMOTE_QISKIT_TOKEN: ${{ secrets.PYTKET_REMOTE_QISKIT_TOKEN }}
  # pytket-qsharp
  PYTKET_REMOTE_QSHARP_RESOURCE_ID: ${{ secrets.PYTKET_REMOTE_QSHARP_RESOURCE_ID }}
  PYTKET_REMOTE_QSHARP_LOCATION: ${{ secrets.PYTKET_REMOTE_QSHARP_LOCATION }}
  PYTKET_REMOTE_QSHARP_STORAGE: ${{ secrets.PYTKET_REMOTE_QSHARP_STORAGE }}
  AZURE_TENANT_ID: ${{ secrets.PYTKET_REMOTE_QSHARP_AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.PYTKET_REMOTE_QSHARP_AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.PYTKET_REMOTE_QSHARP_AZURE_CLIENT_SECRET }}
  # pytket-quantinuum
  PYTKET_REMOTE_QUANTINUUM_USERNAME: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_USERNAME }}
  PYTKET_REMOTE_QUANTINUUM_PASSWORD: ${{ secrets.PYTKET_REMOTE_QUANTINUUM_PASSWORD }}

jobs:
  set-modules-to-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
      - name: Set list of all the pytket extensions
        if: github.event_name != 'pull_request'
        run: |
          cd ${GITHUB_WORKSPACE}/modules
          LS_MODULES=`ls -d */`
          ALL_MODULES=`echo ${LS_MODULES} | sed -e 's/\///g'`
          echo "MODULES_TO_TEST=${ALL_MODULES}" >> $GITHUB_ENV
      - name: Set list of the modified pytket extensions
        if: github.event_name == 'pull_request'
        run : |
          MM=`python3 .github/workflows/changed_modules.py origin/${{ github.base_ref }} ${{ github.sha }}`
          echo "MODULES_TO_TEST=${MM}" >> $GITHUB_ENV
      - name: Set json list of modules to test
        id: set-json-modules-to-test
        run: |
          sudo apt-get install jq
          MODULES_TO_TEST_LIST=($MODULES_TO_TEST)
          echo "::set-output name=modules::$(printf '%s\n' ${MODULES_TO_TEST_LIST[@]} | jq -R . | jq -cs .)"
    outputs:
      matrix: ${{ steps.set-json-modules-to-test.outputs.modules }}

  linux-checks:
    name: Linux - Build and test module
    needs: set-modules-to-test
    runs-on: ubuntu-20.04
    # Skip if PR with no changes to pytket extensions
    if: ${{ ! ( needs.set-modules-to-test.outputs.matrix == '[""]' && github.event_name == 'pull_request') }}

    strategy:
      matrix:
        module: ${{ fromJson(needs.set-modules-to-test.outputs.matrix) }}
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Pull docker images
      if: ${{ matrix.module == 'pytket-pyquil' }}
      run: |
        docker pull rigetti/quilc
        docker pull rigetti/qvm
    - name: Install dotnet SDK
      if: ${{ matrix.module == 'pytket-qsharp' }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install iqsharp
      if: ${{ matrix.module == 'pytket-qsharp' }}
      run: dotnet tool install -g Microsoft.Quantum.IQSharp

    - name: Set up Python 3.8
      if: github.event_name == 'push'
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Build and test (3.8)
      if: github.event_name == 'push'
      run: |
        ./.github/workflows/build-test nomypy
      env:
        MODULE: ${{ matrix.module }}
    - name: Set up Python 3.9
      if: github.event_name == 'pull_request' || github.event_name == 'release' || contains(github.ref, 'refs/heads/wheel')
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build and test including remote checks (3.9)
      if: github.event_name == 'pull_request' || github.event_name == 'release' || contains(github.ref, 'refs/heads/wheel')
      run: |
        ./.github/workflows/build-test nomypy
      env:
        PYTKET_RUN_REMOTE_TESTS: 1
        MODULE: ${{ matrix.module }}
    - name: Set up Python 3.10
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build and test (3.10)
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: |
        ./.github/workflows/build-test nomypy
      env:
        MODULE: ${{ matrix.module }}
    - uses: actions/upload-artifact@v2
      if: github.event_name == 'release' || contains(github.ref, 'refs/heads/wheel')
      with:
        name: artefacts
        path: wheelhouse/

  macos-checks:
    name: MacOS - Build and test module
    needs: set-modules-to-test
    runs-on: macos-11
    if: |
      (github.event_name == 'pull_request' && needs.set-modules-to-test.outputs.matrix != '[""]') ||
      (github.event_name != 'release' && github.event_name != 'pull_request')

    strategy:
      matrix:
        module: ${{ fromJson(needs.set-modules-to-test.outputs.matrix) }}
      fail-fast: false

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Install dotnet SDK
      if: ${{ matrix.module == 'pytket-qsharp' }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install iqsharp
      if: ${{ matrix.module == 'pytket-qsharp' }}
      run: |
        brew install mono-libgdiplus jupyter
        dotnet tool install -g Microsoft.Quantum.IQSharp
        dotnet iqsharp install

    - name: Set up Python 3.8
      if: github.event_name == 'push'
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Build and test (3.8)
      if: github.event_name == 'push'
      run: |
        ./.github/workflows/build-test nomypy
      env:
        MODULE: ${{ matrix.module }}

    - name: Set up Python 3.9
      if: github.event_name == 'pull_request'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build and test including remote checks and mypy (3.9)
      if: github.event_name == 'pull_request'
      run: |
        ./.github/workflows/build-test mypy
      env:
        PYTKET_RUN_REMOTE_TESTS: 1
        MODULE: ${{ matrix.module }}

    - name: Set up Python 3.10
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build and test (3.10)
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: |
        ./.github/workflows/build-test nomypy
      env:
        MODULE: ${{ matrix.module }}

  windows-checks:
    name: Windows - Build and test module
    needs: set-modules-to-test
    runs-on: windows-2019
    if: |
      (github.event_name == 'pull_request' && needs.set-modules-to-test.outputs.matrix != '[""]') ||
      (github.event_name != 'release' && github.event_name != 'pull_request')

    strategy:
      matrix:
        module: ${{ fromJson(needs.set-modules-to-test.outputs.matrix) }}
      fail-fast: false

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*

    - name: Install dotnet SDK
      if: ${{ matrix.module == 'pytket-qsharp' }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install iqsharp
      if: ${{ matrix.module == 'pytket-qsharp' }}
      run: dotnet tool install -g Microsoft.Quantum.IQSharp

    - name: Set up Python 3.8
      if: github.event_name == 'push'
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Build and test (3.8)
      if: github.event_name == 'push'
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
      env:
        MODULE: ${{ matrix.module }}
    - name: Set up Python 3.9
      if: github.event_name == 'pull_request'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build and test including remote checks (3.9)
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
      env:
        PYTKET_RUN_REMOTE_TESTS: 1
        MODULE: ${{ matrix.module }}
    - name: Set up Python 3.10
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build and test (3.10)
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
      env:
        MODULE: ${{ matrix.module }}

  linux:
    name: Build and test (Linux)
    runs-on: ubuntu-20.04
    needs: linux-checks
    steps:
      - name: All linux checks should have succeeded by now
        run: exit 0

  macos:
    if: github.event_name != 'release'
    name: Build and test (MacOS)
    needs: macos-checks
    runs-on: ubuntu-20.04
    steps:
      - name: All macos checks should have succeeded by now
        run: exit 0

  windows:
    if: github.event_name != 'release'
    name: Build and test (Windows)
    needs: windows-checks
    runs-on: ubuntu-20.04
    steps:
      - name: All windows checks should have succeeded by now
        run: exit 0

  publish_to_pypi:
    name: Publish to pypi
    if: github.event_name == 'release'
    needs: linux
    runs-on: ubuntu-20.04
    steps:
    - name: Download all wheels
      uses: actions/download-artifact@v2
      with:
        path: wheelhouse
    - name: Put them all in the dist folder
      run: |
        mkdir dist
        for w in `find wheelhouse/ -type f -name "*.whl"` ; do cp $w dist/ ; done
    - name: Publish wheels
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_EXTENSIONS_API_TOKEN }}
        verbose: true

  docs:
    name: Build and publish docs
    if: github.event_name == 'release'
    needs: publish_to_pypi
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Download all wheels
      uses: actions/download-artifact@v2
      with:
        path: wheelhouse
    - name: Install pip, wheel
      run: pip install -U pip wheel
    - name: Install extensions
      run: for w in `find wheelhouse/ -type f -name "*.whl"` ; do pip install $w ; done
    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install iqsharp
      run: |
        dotnet tool install -g Microsoft.Quantum.IQSharp
        dotnet iqsharp install --user
    - name: Install docs dependencies
      run: |
        pip install -r .github/workflows/docs/requirements.txt
    - name: Build docs
      timeout-minutes: 20
      run: |
        cd .github/workflows/docs
        mkdir extensions
        ./build-docs -a -i -d ${GITHUB_WORKSPACE}/.github/workflows/docs/extensions
    - name: Configure git
      run: |
        git config --global user.email "tket-bot@cambridgequantum.com"
        git config --global user.name  "«$GITHUB_WORKFLOW» github action"
    - name: Check out gh-pages branch
      run: git checkout gh-pages
    - name: Remove old docs
      run: git rm -r --ignore-unmatch docs/api
    - name: Add generated docs to repository
      run: |
        mkdir -p docs
        mv .github/workflows/docs/extensions docs/api
        git add -f docs/api
        git commit --allow-empty -m "Add generated documentation."
    - name: Publish docs
      run:  git push origin gh-pages:gh-pages
