name: Build and test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - 'wheel/**'
      - test-feature-qsharp022-py310
  release:
    types:
      - created
      - edited

env:
  IQSHARP_TELEMETRY_OPT_OUT: 1

jobs:

  windows:
    if: github.event_name != 'release'
    name: Build and test (Windows)
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*

    - name: Determine changed modules
      shell: bash
      run: |
        echo "MODULES_TO_TEST=pytket-qsharp" >> $GITHUB_ENV

    - name: Install dotnet SDK
      if: contains(env.MODULES_TO_TEST, 'pytket-qsharp')
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install iqsharp
      if: contains(env.MODULES_TO_TEST, 'pytket-qsharp')
      run: dotnet tool install -g Microsoft.Quantum.IQSharp

    - name: Set up Python 3.10
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build and test (3.10)
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
