name: Build and test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - 'wheel/**'
      - test-qiskit-310
  release:
    types:
      - created
      - edited

env:
  IQSHARP_TELEMETRY_OPT_OUT: 1

jobs:

  windows:
    if: github.event_name != 'release'
    name: Build and test (Windows)
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Initialize modules list
      shell: bash
      run: |
        echo "MODULES_TO_TEST=pytket-qiskit" >> $GITHUB_ENV
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Build and test (3.10)
      shell: bash
      run: |
        ./.github/workflows/build-test nomypy
