name: Build and test
on:
  push:
    branches:
      - test-qsharp
env:
  IQSHARP_TELEMETRY_OPT_OUT: 1
jobs:
  windows:
    name: Build and test (Windows)
    runs-on: windows-2019
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install iqsharp
      run: |
        dotnet tool install -g Microsoft.Quantum.IQSharp
        pip install jupyter
        dotnet iqsharp install --user
        pip install -U qsharp
        python -c "import qsharp"
