name: Build and test

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop
      - 'wheel/**'
      - gendocs
  release:
    types:
      - created
      - edited

env:
  IQSHARP_TELEMETRY_OPT_OUT: 1

jobs:

  linux:
    name: Build and test (Linux)
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* +refs/heads/*:refs/remotes/origin/*
    - name: Initialize modules list
      run: |
        cd ${GITHUB_WORKSPACE}/modules
        LS_MODULES=`ls -d */`
        ALL_MODULES=`echo ${LS_MODULES} | sed -e 's/\///g'`
        echo "MODULES_TO_TEST=${ALL_MODULES}" >> $GITHUB_ENV
    - name: Pull docker images
      if: contains(env.MODULES_TO_TEST, 'pytket-pyquil')
      run: |
        docker pull rigetti/quilc
        docker pull rigetti/qvm
    - name: Install dotnet SDK
      if: contains(env.MODULES_TO_TEST, 'pytket-qsharp')
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install iqsharp
      if: contains(env.MODULES_TO_TEST, 'pytket-qsharp')
      run: dotnet tool install -g Microsoft.Quantum.IQSharp
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build and test (3.9)
      run: |
        ./.github/workflows/build-test nomypy
    - uses: actions/upload-artifact@v2
      with:
        name: artefacts
        path: wheelhouse/

  docs:
    name: Build and publish docs
    needs: linux
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Download all wheels
      uses: actions/download-artifact@v2
      with:
        path: wheelhouse
    - name: Install pip, wheel
      run: pip install -U pip wheel
    - name: Install extensions
      run: for w in `find wheelhouse/ -type f -name "*.tar.gz"` ; do pip install $w ; done
    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install iqsharp
      run: |
        dotnet tool install -g Microsoft.Quantum.IQSharp
        dotnet iqsharp install --user
    - name: Install docs dependencies
      run: |
        pip install -r .github/workflows/docs/requirements.txt
    - name: Build docs
      timeout-minutes: 20
      run: |
        cd .github/workflows/docs
        mkdir extensions
        ./build-docs -a -i -d ${GITHUB_WORKSPACE}/.github/workflows/docs/extensions
    - name: Configure git
      run: |
        git config --global user.email "tket-bot@cambridgequantum.com"
        git config --global user.name  "«$GITHUB_WORKFLOW» github action"
    - name: Check out gh-pages branch
      run: git checkout gh-pages
    - name: Remove old docs
      run: git rm -r --ignore-unmatch docs/api
    - name: Add generated docs to repository
      run: |
        mkdir -p docs
        mv .github/workflows/docs/extensions docs/api
        git add -f docs/api
        git commit --allow-empty -m "Add generated documentation."
    - name: Publish docs
      run:  git push origin gh-pages:gh-pages
