name: Pytket Extensions Docs

on:
  push:
    branches:
      - 'docs/**'
  schedule:
    # 04:00 every weekday morning
    - cron: '0 4 * * 1-5'

jobs:
  docs:
    name: build docs
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip and install wheel
      run: pip install --upgrade pip wheel
    - name: Install pytket extensions
      run: |
        for path in modules/*/
        do
          cd ${path}
          pip install .
          cd ../..
        done
    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install iqsharp
      run: |
        dotnet tool install -g Microsoft.Quantum.IQSharp
        dotnet iqsharp install --user
    - name: Install docs dependencies
      run: |
        pip install -r .github/workflows/docs/requirements.txt

    - name: Test building docs
      timeout-minutes: 20
      run: |
        cd .github/workflows/docs
        mkdir extensions
        ./build-docs -a -i -d ${GITHUB_WORKSPACE}/.github/workflows/docs/extensions
    - uses: actions/upload-artifact@v2
      with:
        name: pytket-extension-docs
        path: .github/workflows/docs/extensions/
