#!/bin/bash

# Fetch modules from the CQC private pypi server.
# Usage: `fetch-modules <username:password> <module1> <module2> ...`
# where each <module> is <name>-<version>, e.g. `pytket-aqt-0.1.1`.

argc=$#
argv=("$@")

CREDENTIALS=${argv[0]}

for (( i=1; i<argc; i++ )); do
    wget https://${CREDENTIALS}@cqcpythonrepository.azurewebsites.net/packages/${argv[i]}.tar.gz
done
